const SHORT_MOVIE_MAX_LENGTH = 40;
const QTY_MOVIES_DESKTOP = 7;
const QTY_MOVIES_MOBILE = 5;
const SCREEN_MOBILE_MAX_WIDTH = 570;
const SCREEN_TABLET_MAX_WIDTH = 768;

export {
  SHORT_MOVIE_MAX_LENGTH,
  QTY_MOVIES_DESKTOP,
  QTY_MOVIES_MOBILE,
  SCREEN_MOBILE_MAX_WIDTH,
  SCREEN_TABLET_MAX_WIDTH,
};
